package com.afterAll.mybatisGenerator.bean;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.gid
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.g_name
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    private String gName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.g_address
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    private String gAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.gid
     *
     * @return the value of t_group.gid
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.gid
     *
     * @param gid the value for t_group.gid
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.g_name
     *
     * @return the value of t_group.g_name
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.g_name
     *
     * @param gName the value for t_group.g_name
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    public void setgName(String gName) {
        this.gName = gName == null ? null : gName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.g_address
     *
     * @return the value of t_group.g_address
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    public String getgAddress() {
        return gAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.g_address
     *
     * @param gAddress the value for t_group.g_address
     *
     * @mbggenerated Tue May 31 14:58:54 CST 2022
     */
    public void setgAddress(String gAddress) {
        this.gAddress = gAddress == null ? null : gAddress.trim();
    }
}